server:
  port: 8090

app:
  allowed-extensions: jpeg, png, doc, txt, pdf, git
  file-count: 5
  upload-dir: filestorage
  tempory-dir: store_temp_file
  secret-key: secreterandomkey

## MULTIPART (MultipartProperties)
spring:
  servlet:
    multipart:
      enabled: true             #default true
      location: tempLocation    #before save the actual location
      file-size-threshold: 5MB  #Threshold after which files are written to disk
      max-file-size: 1MB
      max-request-size: 20MB

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_file_ref_db?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

temporary:
  files:
    delete:
      cron:
        expression: 0/60 * * * * * # run cron expression every every seconds